spring:
    database:
        driverClassName: com.mysql.jdbc.Driver
    datasource:
        password:
        url: jdbc:mysql://localhost:3306/desafio?useTimezone=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                show_sql: true
